Param (
[switch] $browser
)
# http://stackoverflow.com/questions/8343767/how-to-get-the-current-directory-of-the-cmdlet-being-executed
function Get-ScriptDirectory
{
$Invocation = (Get-Variable MyInvocation -Scope 1).Value
if ($Invocation.PSScriptRoot) {
$Invocation.PSScriptRoot
}
Elseif ($Invocation.MyCommand.Path) {
Split-Path $Invocation.MyCommand.Path
} else {
$Invocation.InvocationName.Substring(0,$Invocation.InvocationName.LastIndexOf(""))
}
}
$shared_assemblies = @(
"WebDriver.dll",
"WebDriver.Support.dll",
"Selenium.WebDriverBackedSelenium.dll",
"nunit.core.dll",
"nunit.framework.dll"
)

$env:SHARED_ASSEMBLIES_PATH = "c:\developer\sergueik\csharp\SharedAssemblies"
$shared_assemblies_path = $env:SHARED_ASSEMBLIES_PATH
pushd $shared_assemblies_path
$shared_assemblies | foreach-object { Unblock-File -Path $_ ; Add-Type -Path $_ }
popd

$verificationErrors = new-object System.Text.StringBuilder
$baseURL = "http://docs.seleniumhq.org/docs/02_selenium_ide.jsp"
$phantomjs_executable_folder = "C:\tools\phantomjs"
if ($PSBoundParameters["browser"]) {
try { 
$connection = (New-Object Net.Sockets.TcpClient)
$connection.Connect("127.0.0.1",4444)
$connection.Close()
} catch {
start-process -filepath "C:\Windows\System32\cmd.exe" -argumentlist "start cmd.exe /c c:\java\selenium\hub.cmd"
start-process -filepath "C:\Windows\System32\cmd.exe" -argumentlist "start cmd.exe /c c:\java\selenium\node.cmd"
start-sleep -seconds 10
}
$capability = [OpenQA.Selenium.Remote.DesiredCapabilities]::Firefox()
$uri = [System.Uri]("http://127.0.0.1:4444/wd/hub")
$selenium = new-object OpenQA.Selenium.Remote.RemoteWebDriver($uri , $capability)
} else {
$selenium = new-object OpenQA.Selenium.PhantomJS.PhantomJSDriver($phantomjs_executable_folder)
$selenium.Capabilities.SetCapability("ssl-protocol", "any" )
$selenium.Capabilities.SetCapability("ignore-ssl-errors", $true)
$selenium.capabilities.SetCapability("takesScreenshot", $true )
$selenium.capabilities.SetCapability("userAgent", "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.7 Safari/534.34")
$options = new-object OpenQA.Selenium.PhantomJS.PhantomJSOptions
$options.AddAdditionalCapability("phantomjs.executable.path", $phantomjs_executable_folder)
}
# WebDriver script generated by Selenium IDE formatter
# example usage:
# $queryBox.SendKeys([OpenQA.Selenium.Keys]::ArrowDown)
# $queryBox.Submit()
# $driver.FindElement([OpenQA.Selenium.By]::LinkText("Selenium (software)")).Click()
# $title =  $driver.Title
# $driver.Quit()

            $selenium.Navigate().GoToUrl($baseURL + "")
            $selenium.FindElement([OpenQA.Selenium.By]::Id("hplogo")).Click()
            # ERROR: Caught exception [Error: unknown strategy [class] for locator [class=gbqfif]]
            $selenium.FindElement([OpenQA.Selenium.By]::CssSelector("input#gbqfq")).Clear()
            $selenium.FindElement([OpenQA.Selenium.By]::CssSelector("input#gbqfq")).SendKeys("selenium")
            $selenium.FindElement([OpenQA.Selenium.By]::Id("gbqfb")).Click()
            $selenium.Navigate().Back()
            [NUnit.Framework.Assert]::IsTrue([Selenium.Internal.SeleniumEmulation]::IsElementPresent([OpenQA.Selenium.By]::Id("hplogo")))
            # ERROR: Caught exception [ERROR: Unsupported command [highlight | id=gbqfb | ]]
# Cleanup
try {
$selenium.Quit()
} catch [Exception] {
# Ignore errors if unable to close the browser
}
[NUnit.Framework.Assert]::AreEqual($verificationErrors.Length, 0)